definitions:
  models.BFFCreateUserRequest:
    properties:
      confirmPassword:
        example: Secure@123
        minLength: 8
        type: string
      email:
        example: arijit@gmail.com
        type: string
      panCard:
        example: EQZRP1234P
        type: string
      password:
        example: Secure@123
        maxLength: 20
        minLength: 8
        type: string
      phoneNumber:
        example: 7568912340
        maximum: 9999999999
        minimum: 1000000000
        type: integer
      username:
        example: Arijit
        maxLength: 32
        minLength: 5
        type: string
    required:
    - confirmPassword
    - email
    - panCard
    - password
    - phoneNumber
    - username
    type: object
  models.ErrorAPIResponse:
    properties:
      error:
        type: string
      errors:
        $ref: '#/definitions/models.ErrorMessage'
    type: object
  models.ErrorMessage:
    properties:
      errorMessage:
        type: string
      key:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/signup:
    post:
      consumes:
      - application/json
      description: Handles user registration by validating input and storing user
        details
      parameters:
      - description: User Registration Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFCreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: string
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
      summary: Create a new user
      tags:
      - User
swagger: "2.0"
